In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[1.0745e-38, 1.1112e-38, 1.0194e-38],
        [1.0653e-38, 5.9694e-39, 8.9082e-39],
        [1.0194e-38, 9.1837e-39, 6.7041e-39],
        [1.0561e-38, 8.9082e-39, 9.9184e-39],
        [9.9184e-39, 9.0000e-39, 1.0561e-38]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.1617, 0.5310, 0.9475],
        [0.2381, 0.0622, 0.2843],
        [0.1293, 0.5880, 0.8707],
        [0.4205, 0.4452, 0.1861],
        [0.3645, 0.5618, 0.0843]])


In [4]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[-0.5269,  1.0086,  1.4336],
        [-0.5566,  0.8864, -0.6130],
        [ 1.1196,  1.5807, -1.0761],
        [ 0.0046,  0.1851, -0.8567],
        [-2.1457,  0.1341, -0.1224]])


In [9]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])
