In [6]:
import torch
import numpy as np

In [4]:
a = torch.ones(5)
b = a.numpy()
print(a,b)
a += 1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [5]:
b += 1
print(a,b)

tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [7]:
#numpy to tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)
a +=1
print(a,b)
b +=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [8]:
c = torch.tensor(a)#torch.tensor()将numpy数组转换成Tensor，会进行数据拷贝，不在共享内存。而之前的方法会共享内存。
a +=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
