In [1]:
import torch

In [4]:
x = torch.empty(5,3)

In [5]:
x = torch.randn_like(x,dtype=torch.float)

In [6]:
y = torch.rand(5,3)
print(x + y)

tensor([[-0.9090,  0.4223,  1.4681],
        [ 0.8408,  0.0901, -0.7545],
        [-0.5929,  2.4216, -0.4295],
        [-0.8655, -1.3516,  0.7628],
        [ 0.5245,  1.2174,  0.5253]])


In [7]:
print(torch.add(x,y))

tensor([[-0.9090,  0.4223,  1.4681],
        [ 0.8408,  0.0901, -0.7545],
        [-0.5929,  2.4216, -0.4295],
        [-0.8655, -1.3516,  0.7628],
        [ 0.5245,  1.2174,  0.5253]])


In [8]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[-0.9090,  0.4223,  1.4681],
        [ 0.8408,  0.0901, -0.7545],
        [-0.5929,  2.4216, -0.4295],
        [-0.8655, -1.3516,  0.7628],
        [ 0.5245,  1.2174,  0.5253]])


In [9]:
#adds x to y
y.add_(x)
print(y)

tensor([[-0.9090,  0.4223,  1.4681],
        [ 0.8408,  0.0901, -0.7545],
        [-0.5929,  2.4216, -0.4295],
        [-0.8655, -1.3516,  0.7628],
        [ 0.5245,  1.2174,  0.5253]])


In [10]:
y = x[0,:]
y += 1
print(y)
print(x[0,:])

tensor([-0.1894,  0.8908,  2.0753])
tensor([-0.1894,  0.8908,  2.0753])


In [11]:
y = x.view(15)
z = x.view(-1,5)
print(x.size(),y.size(),z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [12]:
x += 1
print(x)
print(y)

tensor([[ 0.8106,  1.8908,  3.0753],
        [ 1.0988,  0.8998, -0.2208],
        [ 0.2172,  2.7402, -0.1990],
        [-0.5330, -0.8807,  0.9748],
        [ 1.2655,  2.0819,  1.1184]])
tensor([ 0.8106,  1.8908,  3.0753,  1.0988,  0.8998, -0.2208,  0.2172,  2.7402,
        -0.1990, -0.5330, -0.8807,  0.9748,  1.2655,  2.0819,  1.1184])


In [13]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[-0.1894,  0.8908,  2.0753],
        [ 0.0988, -0.1002, -1.2208],
        [-0.7828,  1.7402, -1.1990],
        [-1.5330, -1.8807, -0.0252],
        [ 0.2655,  1.0819,  0.1184]])
tensor([ 0.8106,  1.8908,  3.0753,  1.0988,  0.8998, -0.2208,  0.2172,  2.7402,
        -0.1990, -0.5330, -0.8807,  0.9748,  1.2655,  2.0819,  1.1184])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9807])
0.9806999564170837
