In [1]:
import torch

In [2]:
x = torch.ones(1,requires_grad=True)
print(x.data)

tensor([1.])


In [3]:
print(x.data.requires_grad)

False


In [4]:
y = 2*x
x.data *= 100
y.backward()
print(x)
print(x.grad)

tensor([100.], requires_grad=True)
tensor([2.])
