In [1]:
import torch

In [25]:
x = torch.ones(2,2,requires_grad=True)
y = x+2
z = y*y*3
out = z.mean()
#out.backward()
print(x.grad)

None


In [26]:
out2 = x.sum()
#out2.backward()
print(x.grad)

None


In [28]:
out3 = x.sum()
#x.grad.data.zero_()
#out3.backward()
print(x.grad)

None


In [13]:
x = torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)
y = 2*x
z = y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [29]:
v = torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
z.backward(v)#这里要把前面的backward注释掉，才能正常运行代码。具体解决方法没找到
print(x.grad)

tensor([[1.8000e+01, 1.8000e+00],
        [1.8000e-01, 1.8000e-02]])


In [30]:
x = torch.tensor(1.0,requires_grad=True)
y1 = x **2
with torch.no_grad():
    y2 = x**3
y3 = y1+y2
print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [31]:
y3.backward()
print(x.grad)

tensor(2.)


In [32]:
x = torch.ones(1,requires_grad=True)
print(x.data)
print(x.data.requires_grad)
y = 2*x
x.data *= 100

y.backward()
print(x)
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
