In [1]:
import torch


In [9]:
x = torch.tensor([[2,2],[3,3]],dtype=float,requires_grad=True)
y = x+2
z = y*y*3
print(y,z)

tensor([[4., 4.],
        [5., 5.]], dtype=torch.float64, grad_fn=<AddBackward0>) tensor([[48., 48.],
        [75., 75.]], dtype=torch.float64, grad_fn=<MulBackward0>)


In [10]:
out = z.mean()
print(z,out)

tensor([[48., 48.],
        [75., 75.]], dtype=torch.float64, grad_fn=<MulBackward0>) tensor(61.5000, dtype=torch.float64, grad_fn=<MeanBackward0>)


In [11]:
out.backward()
print(x.grad)

tensor([[6.0000, 6.0000],
        [7.5000, 7.5000]], dtype=torch.float64)


In [12]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[7.0000, 7.0000],
        [8.5000, 8.5000]], dtype=torch.float64)


In [13]:
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
