In [1]:
import numpy as np
import torch

In [12]:
x = torch.tensor([[]])

tensor([1., 1., 1.], dtype=torch.float64)


In [13]:
y = x+2
print(y)

tensor([3., 3., 3.], dtype=torch.float64)


In [14]:
z = y*2
print(z)

tensor([6., 6., 6.], dtype=torch.float64)


In [15]:
out  = z.mean()
print(out)

tensor(6., dtype=torch.float64)


In [16]:
out.backward()
print(x.grad)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn