In [1]:
import torch
from torch import nn
torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
x = torch.tensor(1)
x_cuda = x.cuda()

In [5]:
print(torch.__version__)


1.5.1


In [6]:
torch.cuda.get_device_name(0)

'GeForce 940M'

In [8]:
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [9]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [10]:
x.device

device(type='cuda', index=0)

In [12]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x = torch.tensor([1,2,3],device=device)
#or
x = torch.tensor([1,2,3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [13]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [14]:
z = y +x.cpu()#因为一个在CPU一个在GPU，所以直接运算会报错

RuntimeError: expected device cuda:0 but got device cpu

In [15]:
net = nn.Linear(3,1)
list(net.parameters())[0].device#通过检查模型的参数的device属性来查看存放模型的设备

device(type='cpu')

In [16]:
#通过上面代码，pytorch原来在CPU上，现在通过.cuda转换到GPU上
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [17]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[0.1428],
        [0.1185]], device='cuda:0', grad_fn=<AddmmBackward>)