In [1]:
import torch

In [9]:
a = torch.Tensor([[1,2],[3,4]])
b = torch.gather(a,dim=0,index=torch.LongTensor([[0,1]]))

In [10]:
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 4.]])


In [11]:
# a的dim=0,即 行方向的维度和index的维度是匹配的，就是说，a和index由行方向从左往右看，
# 有2列，即有2个样本，行方向是匹配的。另外，函数输出的Tensor和index大小相同
#以上代码逻辑：由行从左往右看，有两个样本，索引分别为0和1；每个样本有两个特征，
#每个特征中从上往下索引分别为0和1；依据index中的索引值，取第0样本的第0个特征，
#再取第1个样本的第1个特征

In [21]:
c = torch.Tensor([[11,22],[33,44]])
d = torch.gather(c,dim=1,index=torch.LongTensor([[0],[1]]))

In [22]:
print(c)
print(d)

tensor([[11., 22.],
        [33., 44.]])
tensor([[11.],
        [44.]])


In [23]:
#由列从上往下看，有两个样本，索引分别为0和1；每个样本有两个特征
#每个特征中从左往右索引分别为0和1；依据index中的索引值，取第0个样本的第0个特别
#再取第一个样本的第一个特征

In [27]:
e = torch.Tensor([[1,2],[3,4]])
f = torch.gather(e,dim=0,index=torch.LongTensor([[0,0],[1,0]]))

In [29]:
print('a = ',e)
print('b = ',f)

a =  tensor([[1., 2.],
        [3., 4.]])
b =  tensor([[1., 2.],
        [3., 2.]])


In [ ]:
#LongTensor是64位整型